// Generated by Selenium IDE
package com.sample.DemologinTest;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DemologinTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void demologin() {
    driver.get("https://github.com/");
    driver.manage().window().setSize(new Dimension(1058, 670));
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("login_field")).sendKeys("chimkodeashwini90@gmail.com");
    driver.findElement(By.id("password")).sendKeys("ashwini_c9021");
    driver.findElement(By.cssSelector(".auth-form-body")).click();
    driver.findElement(By.cssSelector("main")).click();
    driver.findElement(By.cssSelector("main")).click();
    driver.findElement(By.name("commit")).click();
    driver.findElement(By.cssSelector(".d-inline")).click();
    driver.findElement(By.linkText("Issues")).click();
    driver.findElement(By.cssSelector(".dropdown-caret:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".dropdown-signout")).click();
    driver.findElement(By.cssSelector("html")).click();
  }
}
